name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/App/requirements.txt
          
      - name: Start Flask server
        run: |
          nohup python backend/App/endPoints.py &
        env:
          FLASK_APP: backend/App/endPoints.py
          FLASK_ENV: development

      - name: Create database directory
        run: |
          mkdir -p backend/App

      - name: Check database path
        run: |
          echo "Database path: $(pwd)/backend/App/accounts.db"
          touch backend/App/accounts.db
      
      - name: Run tests
        run: |
          cd backend/Tests
          pytest tests.py
